FROM neo4j:4.0.6-enterprise
COPY ./gds/neo4j-graph-data-science-1.3.0-standalone.jar /var/lib/neo4j/plugins/gds.jar
#COPY ./ml/neo4j-ml-models-1.0.2.jar /var/lib/neo4j/plugins/neo4j-ml-models-1.0.2.jar
#COPY ./nlp/stanford-english-corenlp-2018-10-05-models.jar /var/lib/neo4j/plugins/stanford.jar
EXPOSE 7474 7687 
