version: '3.7'
services:
  neo4j:
    container_name: ${PROJECT}-neo4j
    env_file:
      - .env
    restart: on-failure
    build:
      context: ./neo4j
      dockerfile: Dockerfile
    ports:
      - "7474:7474/tcp"
      - "7687:7687/tcp"
    volumes:
      - ./neo4j:/neo4j
    deploy:
      replicas: 1

  kafka:
    container_name: ${PROJECT}-kafka
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092
      KAFKA_BROKER_ID: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:32181
    image: confluentinc/cp-kafka:latest
    ports:
      - "29092:29092/tcp"
    deploy:
      replicas: 1

  zookeeper:
    container_name: ${PROJECT}-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 32181
      ZOOKEEPER_TICK_TIME: 2000
    image: confluentinc/cp-zookeeper:latest
    ports:
      - "32181:32181/tcp"
    deploy:
      replicas: 1
