version: '3.7'
services:
  neo4j:
    container_name: ${PROJECT}-neo4j
    env_file:
      - .env
    restart: on-failure
    build:
      context: ./neo4j
      dockerfile: Dockerfile
    ports:
      - "7474:7474/tcp"
      - "7687:7687/tcp"
    volumes:
      - ./neo4j:/neo4j
    deploy:
      replicas: 1


  kafka:
    container_name: ${PROJECT}-kafka
    env_file:
      - .env
    image: confluentinc/cp-kafka:latest
    ports:
      - 29092:29092
      - 9092:9092
    deploy:
      replicas: 1
    depends_on:
      - zookeeper
  #  volumes:
  #    - kafka_data:/var/lib/kafka/data  


  zookeeper:
    container_name: ${PROJECT}-zookeeper
    image: confluentinc/cp-zookeeper:latest
    env_file:
      - .env
    ports:
      - 32181:32181
      - 2181:2181
    volumes:
      - zoo_data:/data
      - zoo_datalog:/datalog
    deploy:
      replicas: 1

  slackbot:
    container_name: ${PROJECT}-slack-bot
    build: ./slackbot
    env_file:
      - .env
    depends_on:
      - daemon
      - redis
    command: python run.py


#  lex:
#    container_name: ${PROJECT}-lex
#    build: ./lex
#    ports:
#      - "8888:8888/tcp"
#    env_file:
#      - .env
#    command: python run.py


  daemon:
    container_name: ${PROJECT}_daemon
    build:
      context: ./daemon
      dockerfile: Dockerfile
    restart: always
    ports:
     - "8001:8001"
    env_file:
      - .env
    depends_on:
      - kafka
      - redis
    volumes:
      - './daemon/:/usr/app'


  #broker:
  #  container_name: ${PROJECT}-broker
  #  build: ./broker
  #  env_file:
  #    - .env
  #  depends_on:
  #    - kafka
  #  #command: faust -A app worker -l info

  schema-registry:
    image: confluentinc/cp-schema-registry:5.4.0
    hostname: schema-registry
    container_name: ${PROJECT}-schema-registry
    depends_on:
      - zookeeper
      - kafka
    ports:
      - "8081:8081"
    environment:
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL: "zookeeper:2181"

  redis:
    container_name: ${PROJECT}_redis
    image: redis
    ports:
      - "6379:6379"
    env_file:
      - .env


networks:
  neo4j_net:
    driver: bridge

volumes:
  neo4j_logs:
  neo4j_import:
  neo4j_plugins:
  neo4j_conf:
  neo4j_data:
  dgraph:
  pg_data:
  neo4j_graphaware:
  kafka_data:
  sink_plugins:
  zoo_data:
  zoo_datalog:
