FROM circleci/node:latest-browsers

WORKDIR /usr/src/app/
USER root
COPY package.json ./
RUN yarn

COPY ./ ./

RUN yarn start
#npm run test:all

#RUN npm run fetch:blocks

EXPOSE 8000

CMD ["npm", "run", "build"]
